<?php
/**
 *
 * WARNING: Please do not edit this file
 *
 * We load all our functions from
 * the includes directory.
 */
require ( get_template_directory() . '/includes/functions.php' );
require ( get_template_directory() . '/includes/classes/class.Options.php' );


/** 
 * Theme Specific Function can be included bellow 
 */

    /** -----------------------------------------------------
     * Creating a few custom post types 
     * And a few taxonomies
     * ------------------------------------------------------
     */

//    require_once('includes/classes/class.Custom_Post_Types.php');
//    
//    $bckFunctionofDay = new Custom_Post_Types('bck-daily-tip', 'Daily Tip', 'Daily Tip', 'bck-daily-tip');
//    $bckFunctionofDay->jdevSupports = array( 'title', 'editor', 'excerpt' );